DEVOPS-00: Add error output

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,6 +9,10 @@ inputs:
     description: "Forces a re-evaluation of the entire git history."
     required: false
     default: 'false'
+  force-patch-increment:
+    description: "Forces a PATCH increment if no other increment detected. NOTE: This is intended for development purposes only."
+    required: false
+    default: 'false'
 outputs:
   new-version:
     description: "New Version"
@@ -33,9 +37,25 @@ runs:
           cd $GITHUB_WORKSPACE
           opt=''
           [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-f'
+          [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-p'
           new_version="$(${{ github.action_path }}/scripts/detectNewVersion.sh $opt)"
           echo "new-version=$new_version" | tee $GITHUB_OUTPUT
-          [[ "$new_version" =~ "ERROR" ]] && exit 1 || true
+          if [[ "$new_version" =~ "570" ]]; then
+            echo -e "\e[01;31mERROR\e[00m: 570 - Invalid argument!"
+            exit 1 || true
+          fi
+          if [[ "$new_version" =~ "590" ]]; then
+            echo -e "\e[01;31mFATAL\e[00m: 501 - This is not a git repository!"
+            exit 1 || true
+          fi
+          if [[ "$new_version" =~ "591" ]]; then
+            echo -e "\e[01;31mERROR\e[0m: 591 - Unsupported origin host."
+            exit 1 || true
+          fi
+          if [[ "$new_version" =~ "599" ]]; then
+            echo -e "\e[01;31mERROR\e[00m: 599 - No feature, enhancement, fix, bugfix, hotfix, or ops branches detected!"
+            exit 1 || true
+          fi
       shell: bash
 
 # See github contexts for more like github.action_path.
