Fix arg handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -37,7 +37,7 @@ runs:
           cd $GITHUB_WORKSPACE
           opt=''
           [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-f'
-          [[ "${{ inputs.force-re-evaluate }}" == 'true' ]] && opt='-p'
+          [[ "${{ inputs.force-patch-increment }}" == 'true' ]] && opt='-p'
           new_version="$(${{ github.action_path }}/scripts/detectNewVersion.sh $opt)"
           echo "new-version=$new_version" | tee $GITHUB_OUTPUT
           if [[ "$new_version" =~ "570" ]]; then
@@ -54,6 +54,10 @@ runs:
           fi
           if [[ "$new_version" =~ "599" ]]; then
             echo -e "\e[01;31mERROR\e[00m: 599 - No feature, enhancement, fix, bugfix, hotfix, or ops branches detected!"
+            exit 1 || true
+          fi
+          if [[ "$new_version" =~ "520" ]]; then
+            echo -e "\e[01;31mERROR\e[00m: 599 -  - You must source this script when specifying an environment variable! Eg: '. ./foo.sh -e bar_ver'"
             exit 1 || true
           fi
       shell: bash
